FROM irislib:latest

# RUN git clone https://github.com/flutter/flutter.git -b stable

RUN wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.12.13+hotfix.8-stable.tar.xz && \
    tar xf ~/Downloads/flutter_linux_v1.12.13+hotfix.8-stable.tar.xz

